// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Dv7h1EzHSo0oikxlKl_ktfoEhFmtmL0',
    appId: '1:467565888661:web:f1c797da1023ab1396c79c',
    messagingSenderId: '467565888661',
    projectId: 'hajimeapp-20e2f',
    authDomain: 'hajimeapp-20e2f.firebaseapp.com',
    storageBucket: 'hajimeapp-20e2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwrHjhMDO1mmVivSt5gTQ_6tgExhIWsdM',
    appId: '1:467565888661:android:9cc4e4a66d3c4d8796c79c',
    messagingSenderId: '467565888661',
    projectId: 'hajimeapp-20e2f',
    storageBucket: 'hajimeapp-20e2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAZJE4GUiryn-hhc7eeiMjvYNxsDR-26c',
    appId: '1:467565888661:ios:0e099ef144e567e596c79c',
    messagingSenderId: '467565888661',
    projectId: 'hajimeapp-20e2f',
    storageBucket: 'hajimeapp-20e2f.appspot.com',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAZJE4GUiryn-hhc7eeiMjvYNxsDR-26c',
    appId: '1:467565888661:ios:0e099ef144e567e596c79c',
    messagingSenderId: '467565888661',
    projectId: 'hajimeapp-20e2f',
    storageBucket: 'hajimeapp-20e2f.appspot.com',
    iosBundleId: 'com.example.flutterTest1',
  );
}
